// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechNova_IT_Solutions.Data;

#nullable disable

namespace TechNova_IT_Solutions.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210235406_ClearAllDataExceptAccounts")]
    partial class ClearAllDataExceptAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechNova_IT_Solutions.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("logID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("action");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("logdate");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("module");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("Audit_Logs");

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            Action = "Login",
                            LogDate = new DateTime(2026, 2, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Module = "Authentication",
                            UserId = 1
                        },
                        new
                        {
                            LogId = 2,
                            Action = "Login",
                            LogDate = new DateTime(2026, 2, 10, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            Module = "Authentication",
                            UserId = 2
                        },
                        new
                        {
                            LogId = 3,
                            Action = "Create Policy",
                            LogDate = new DateTime(2026, 2, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Module = "Policy Management",
                            UserId = 1
                        },
                        new
                        {
                            LogId = 4,
                            Action = "Login",
                            LogDate = new DateTime(2026, 2, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Module = "Authentication",
                            UserId = 4
                        },
                        new
                        {
                            LogId = 5,
                            Action = "Login",
                            LogDate = new DateTime(2026, 2, 10, 9, 35, 0, 0, DateTimeKind.Unspecified),
                            Module = "Authentication",
                            UserId = 5
                        },
                        new
                        {
                            LogId = 6,
                            Action = "Acknowledge Policy",
                            LogDate = new DateTime(2026, 2, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Module = "Compliance",
                            UserId = 4
                        },
                        new
                        {
                            LogId = 7,
                            Action = "Assign Policy",
                            LogDate = new DateTime(2026, 2, 10, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Module = "Policy Management",
                            UserId = 2
                        },
                        new
                        {
                            LogId = 8,
                            Action = "Login",
                            LogDate = new DateTime(2026, 2, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Module = "Authentication",
                            UserId = 3
                        },
                        new
                        {
                            LogId = 9,
                            Action = "Review Compliance",
                            LogDate = new DateTime(2026, 2, 10, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Module = "Supplier Management",
                            UserId = 3
                        },
                        new
                        {
                            LogId = 10,
                            Action = "Approve Procurement",
                            LogDate = new DateTime(2026, 2, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Module = "Procurement",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ComplianceStatus", b =>
                {
                    b.Property<int>("ComplianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("complianceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplianceId"));

                    b.Property<DateTime?>("AcknowledgedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("acknowledged_date");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignmentID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("ComplianceId");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.ToTable("Compliance_Status");

                    b.HasData(
                        new
                        {
                            ComplianceId = 1,
                            AcknowledgedDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignmentId = 1,
                            Status = "Acknowledged"
                        },
                        new
                        {
                            ComplianceId = 2,
                            AcknowledgedDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignmentId = 2,
                            Status = "Acknowledged"
                        },
                        new
                        {
                            ComplianceId = 3,
                            AssignmentId = 3,
                            Status = "Pending"
                        },
                        new
                        {
                            ComplianceId = 4,
                            AcknowledgedDate = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignmentId = 4,
                            Status = "Acknowledged"
                        },
                        new
                        {
                            ComplianceId = 5,
                            AcknowledgedDate = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignmentId = 5,
                            Status = "Acknowledged"
                        },
                        new
                        {
                            ComplianceId = 6,
                            AcknowledgedDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignmentId = 6,
                            Status = "Acknowledged"
                        },
                        new
                        {
                            ComplianceId = 7,
                            AssignmentId = 7,
                            Status = "Pending"
                        },
                        new
                        {
                            ComplianceId = 8,
                            AcknowledgedDate = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignmentId = 8,
                            Status = "Acknowledged"
                        },
                        new
                        {
                            ComplianceId = 9,
                            AssignmentId = 9,
                            Status = "Overdue"
                        },
                        new
                        {
                            ComplianceId = 10,
                            AssignmentId = 10,
                            Status = "Pending"
                        },
                        new
                        {
                            ComplianceId = 11,
                            AcknowledgedDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignmentId = 11,
                            Status = "Acknowledged"
                        },
                        new
                        {
                            ComplianceId = 12,
                            AssignmentId = 12,
                            Status = "Pending"
                        },
                        new
                        {
                            ComplianceId = 13,
                            AcknowledgedDate = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignmentId = 13,
                            Status = "Acknowledged"
                        },
                        new
                        {
                            ComplianceId = 14,
                            AcknowledgedDate = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignmentId = 14,
                            Status = "Acknowledged"
                        },
                        new
                        {
                            ComplianceId = 15,
                            AcknowledgedDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AssignmentId = 15,
                            Status = "Acknowledged"
                        },
                        new
                        {
                            ComplianceId = 16,
                            AssignmentId = 16,
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("policyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("DateUploaded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_uploaded");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("PolicyTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("policy_title");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.HasKey("PolicyId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            PolicyId = 1,
                            Category = "Data Privacy",
                            DateUploaded = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comprehensive policy covering GDPR and data protection requirements for handling customer and employee data.",
                            FilePath = "/policies/data-privacy-policy.pdf",
                            PolicyTitle = "Data Privacy and Protection Policy",
                            UploadedBy = 1
                        },
                        new
                        {
                            PolicyId = 2,
                            Category = "Security",
                            DateUploaded = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Guidelines for maintaining information security, including password management, access controls, and incident reporting.",
                            FilePath = "/policies/info-security-policy.pdf",
                            PolicyTitle = "Information Security Policy",
                            UploadedBy = 1
                        },
                        new
                        {
                            PolicyId = 3,
                            Category = "HR",
                            DateUploaded = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Professional conduct standards and ethical guidelines for all TechNova employees.",
                            FilePath = "/policies/code-of-conduct.pdf",
                            PolicyTitle = "Code of Conduct",
                            UploadedBy = 2
                        },
                        new
                        {
                            PolicyId = 4,
                            Category = "HR",
                            DateUploaded = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Guidelines and requirements for employees working remotely, including security and communication protocols.",
                            FilePath = "/policies/remote-work-policy.pdf",
                            PolicyTitle = "Remote Work Policy",
                            UploadedBy = 2
                        },
                        new
                        {
                            PolicyId = 5,
                            Category = "Procurement",
                            DateUploaded = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Standards and expectations for supplier behavior, including ethical practices and compliance requirements.",
                            FilePath = "/policies/supplier-code-conduct.pdf",
                            PolicyTitle = "Supplier Code of Conduct",
                            UploadedBy = 1
                        },
                        new
                        {
                            PolicyId = 6,
                            Category = "Operations",
                            DateUploaded = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Framework for ensuring business operations continue during disruptions and emergencies.",
                            FilePath = "/policies/business-continuity-policy.pdf",
                            PolicyTitle = "Business Continuity Policy",
                            UploadedBy = 3
                        });
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.PolicyAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_date");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policyID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("AssignmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("PolicyId", "UserId")
                        .IsUnique();

                    b.ToTable("Policy_Assignments");

                    b.HasData(
                        new
                        {
                            AssignmentId = 1,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 1,
                            UserId = 4
                        },
                        new
                        {
                            AssignmentId = 2,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 2,
                            UserId = 4
                        },
                        new
                        {
                            AssignmentId = 3,
                            AssignedDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 3,
                            UserId = 4
                        },
                        new
                        {
                            AssignmentId = 4,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 1,
                            UserId = 5
                        },
                        new
                        {
                            AssignmentId = 5,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 2,
                            UserId = 5
                        },
                        new
                        {
                            AssignmentId = 6,
                            AssignedDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 3,
                            UserId = 5
                        },
                        new
                        {
                            AssignmentId = 7,
                            AssignedDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 4,
                            UserId = 5
                        },
                        new
                        {
                            AssignmentId = 8,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 1,
                            UserId = 6
                        },
                        new
                        {
                            AssignmentId = 9,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 2,
                            UserId = 6
                        },
                        new
                        {
                            AssignmentId = 10,
                            AssignedDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 4,
                            UserId = 6
                        },
                        new
                        {
                            AssignmentId = 11,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 2,
                            UserId = 7
                        },
                        new
                        {
                            AssignmentId = 12,
                            AssignedDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 3,
                            UserId = 7
                        },
                        new
                        {
                            AssignmentId = 13,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 1,
                            UserId = 8
                        },
                        new
                        {
                            AssignmentId = 14,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 2,
                            UserId = 8
                        },
                        new
                        {
                            AssignmentId = 15,
                            AssignedDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 3,
                            UserId = 8
                        },
                        new
                        {
                            AssignmentId = 16,
                            AssignedDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = 6,
                            UserId = 8
                        });
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Procurement", b =>
                {
                    b.Property<int>("ProcurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("procurementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcurementId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("ItemName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("item_name");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("RelatedPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("related_policyID");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    b.HasKey("ProcurementId");

                    b.HasIndex("RelatedPolicyId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Procurement");

                    b.HasData(
                        new
                        {
                            ProcurementId = 1,
                            Category = "Cloud Services",
                            ItemName = "Cloud Infrastructure Services - Annual Subscription",
                            PurchaseDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1,
                            RelatedPolicyId = 5,
                            SupplierId = 1
                        },
                        new
                        {
                            ProcurementId = 2,
                            Category = "Software",
                            ItemName = "Cybersecurity Software Licenses",
                            PurchaseDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 100,
                            RelatedPolicyId = 2,
                            SupplierId = 2
                        },
                        new
                        {
                            ProcurementId = 3,
                            Category = "Hardware",
                            ItemName = "Laptop Computers - Dell XPS 15",
                            PurchaseDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 25,
                            SupplierId = 4
                        },
                        new
                        {
                            ProcurementId = 4,
                            Category = "Cloud Services",
                            ItemName = "Data Backup and Recovery Services",
                            PurchaseDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1,
                            RelatedPolicyId = 6,
                            SupplierId = 1
                        },
                        new
                        {
                            ProcurementId = 5,
                            Category = "Services",
                            ItemName = "IT Support Services - Quarterly Contract",
                            PurchaseDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1,
                            SupplierId = 3
                        });
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("ContactPersonFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_person_fname");

                    b.Property<string>("ContactPersonLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_person_lname");

                    b.Property<string>("ContactPersonNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_person_number");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("supplier_name");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "123 Tech Boulevard, Silicon Valley, CA 94025",
                            ContactPersonFirstName = "Robert",
                            ContactPersonLastName = "Anderson",
                            ContactPersonNumber = "+1-555-0101",
                            Email = "robert.anderson@cloudtech.com",
                            Status = "Active",
                            SupplierName = "CloudTech Solutions Inc"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "456 Security Street, Boston, MA 02101",
                            ContactPersonFirstName = "Jennifer",
                            ContactPersonLastName = "Lee",
                            ContactPersonNumber = "+1-555-0102",
                            Email = "jennifer.lee@securedata.com",
                            Status = "Active",
                            SupplierName = "SecureData Corp"
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "789 Enterprise Drive, Austin, TX 78701",
                            ContactPersonFirstName = "David",
                            ContactPersonLastName = "Kumar",
                            ContactPersonNumber = "+1-555-0103",
                            Email = "david.kumar@globalit.com",
                            Status = "Active",
                            SupplierName = "Global IT Services Ltd"
                        },
                        new
                        {
                            SupplierId = 4,
                            Address = "321 Hardware Lane, Seattle, WA 98101",
                            ContactPersonFirstName = "Maria",
                            ContactPersonLastName = "Santos",
                            ContactPersonNumber = "+1-555-0104",
                            Email = "maria.santos@techhardware.com",
                            Status = "Inactive",
                            SupplierName = "TechHardware Supplies"
                        });
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.SupplierPolicy", b =>
                {
                    b.Property<int>("SupplierPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplier_policiesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierPolicyId"));

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_date");

                    b.Property<string>("ComplianceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("compliance_status");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policyID");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    b.HasKey("SupplierPolicyId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("SupplierId", "PolicyId")
                        .IsUnique();

                    b.ToTable("Supplier_Policies");

                    b.HasData(
                        new
                        {
                            SupplierPolicyId = 1,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ComplianceStatus = "Compliant",
                            PolicyId = 5,
                            SupplierId = 1
                        },
                        new
                        {
                            SupplierPolicyId = 2,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ComplianceStatus = "Compliant",
                            PolicyId = 5,
                            SupplierId = 2
                        },
                        new
                        {
                            SupplierPolicyId = 3,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ComplianceStatus = "Compliant",
                            PolicyId = 1,
                            SupplierId = 2
                        },
                        new
                        {
                            SupplierPolicyId = 4,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ComplianceStatus = "Pending",
                            PolicyId = 5,
                            SupplierId = 3
                        },
                        new
                        {
                            SupplierPolicyId = 5,
                            AssignedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ComplianceStatus = "Non-Compliant",
                            PolicyId = 5,
                            SupplierId = 4
                        });
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@technova.com",
                            FirstName = "System",
                            LastName = "Administrator",
                            Password = "Admin@123",
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "sarah.johnson@technova.com",
                            FirstName = "Sarah",
                            LastName = "Johnson",
                            Password = "Compliance@123",
                            Role = "ComplianceManager",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "michael.chen@technova.com",
                            FirstName = "Michael",
                            LastName = "Chen",
                            Password = "Compliance@123",
                            Role = "ComplianceManager",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "emma.williams@technova.com",
                            FirstName = "Emma",
                            LastName = "Williams",
                            Password = "Employee@123",
                            Role = "Employee",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "james.brown@technova.com",
                            FirstName = "James",
                            LastName = "Brown",
                            Password = "Employee@123",
                            Role = "Employee",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "olivia.martinez@technova.com",
                            FirstName = "Olivia",
                            LastName = "Martinez",
                            Password = "Employee@123",
                            Role = "Employee",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "william.davis@technova.com",
                            FirstName = "William",
                            LastName = "Davis",
                            Password = "Employee@123",
                            Role = "Employee",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "sophia.garcia@technova.com",
                            FirstName = "Sophia",
                            LastName = "Garcia",
                            Password = "Employee@123",
                            Role = "Employee",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "liam.rodriguez@technova.com",
                            FirstName = "Liam",
                            LastName = "Rodriguez",
                            Password = "Employee@123",
                            Role = "Employee",
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.AuditLog", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ComplianceStatus", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.PolicyAssignment", "PolicyAssignment")
                        .WithOne("ComplianceStatus")
                        .HasForeignKey("TechNova_IT_Solutions.Models.ComplianceStatus", "AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Policy", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.User", "UploadedByUser")
                        .WithMany("UploadedPolicies")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.PolicyAssignment", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "Policy")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechNova_IT_Solutions.Models.User", "User")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Procurement", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "RelatedPolicy")
                        .WithMany("Procurements")
                        .HasForeignKey("RelatedPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechNova_IT_Solutions.Models.Supplier", "Supplier")
                        .WithMany("Procurements")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedPolicy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.SupplierPolicy", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "Policy")
                        .WithMany("SupplierPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechNova_IT_Solutions.Models.Supplier", "Supplier")
                        .WithMany("SupplierPolicies")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Policy", b =>
                {
                    b.Navigation("PolicyAssignments");

                    b.Navigation("Procurements");

                    b.Navigation("SupplierPolicies");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.PolicyAssignment", b =>
                {
                    b.Navigation("ComplianceStatus");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Supplier", b =>
                {
                    b.Navigation("Procurements");

                    b.Navigation("SupplierPolicies");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("PolicyAssignments");

                    b.Navigation("UploadedPolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
