// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechNova_IT_Solutions.Data;

#nullable disable

namespace TechNova_IT_Solutions.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260303130025_SeedSuperAdminAccount")]
    partial class SeedSuperAdminAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechNova_IT_Solutions.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("logID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("action");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("logdate");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("module");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("Audit_Logs");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("branchId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("branchName");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("ManagerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("managerEmail");

                    b.Property<string>("ManagerFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("managerFirstName");

                    b.Property<string>("ManagerLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("managerLastName");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("region");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ComplianceStatus", b =>
                {
                    b.Property<int>("ComplianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("complianceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplianceId"));

                    b.Property<DateTime?>("AcknowledgedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("acknowledged_date");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignmentID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("ComplianceId");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.ToTable("Compliance_Status");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ComplianceViolation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("violationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViolationId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("PolicyAssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    b.Property<int?>("RaisedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("raised_by_user_id");

                    b.Property<DateTime>("RaisedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("raised_date");

                    b.Property<string>("Resolution")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_date");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("severity_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<int?>("SupplierPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_policy_id");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("violation_type");

                    b.HasKey("ViolationId");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("RaisedByUserId");

                    b.HasIndex("SupplierPolicyId");

                    b.ToTable("compliance_violations");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ExternalPolicyImport", b =>
                {
                    b.Property<int>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("importID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportId"));

                    b.Property<int?>("ApprovedPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("approved_policy_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("document_number");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("external_url");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("imported_at");

                    b.Property<int?>("ImportedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("imported_by_user_id");

                    b.Property<string>("PolicyTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("policy_title");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("publication_date");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("review_notes");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("review_status");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("SourceApi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("source_api");

                    b.HasKey("ImportId");

                    b.HasIndex("ApprovedPolicyId");

                    b.HasIndex("ImportedByUserId");

                    b.HasIndex("ReviewStatus");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("SourceApi", "DocumentNumber");

                    b.ToTable("External_Policy_Imports");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("policyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime?>("ArchivedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("archived_date");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("branch_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("DateUploaded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_uploaded");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_path");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("is_archived");

                    b.Property<string>("PendingCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pending_category");

                    b.Property<string>("PendingDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pending_description");

                    b.Property<string>("PendingFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("pending_file_path");

                    b.Property<string>("PendingTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pending_title");

                    b.Property<DateTime?>("PendingUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("pending_updated_at");

                    b.Property<int?>("PendingUpdatedBy")
                        .HasColumnType("int")
                        .HasColumnName("pending_updated_by");

                    b.Property<string>("PolicyTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("policy_title");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("review_notes");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("review_status");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.HasKey("PolicyId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.PolicyAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_date");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policyID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("AssignmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("PolicyId", "UserId")
                        .IsUnique();

                    b.ToTable("Policy_Assignments");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Procurement", b =>
                {
                    b.Property<int>("ProcurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("procurementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcurementId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("branch_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("ConversionTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("conversion_timestamp");

                    b.Property<decimal>("ConvertedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("converted_amount");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("DelayReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("delay_reason");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("exchange_rate");

                    b.Property<string>("ItemName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("item_name");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("original_amount");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("received_date");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<int?>("RelatedPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("related_policyID");

                    b.Property<DateTime?>("RevisedDeliveryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("revised_delivery_date");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("shipment_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SupplierCommitShipDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("supplier_commit_ship_date");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    b.Property<DateTime?>("SupplierResponseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("supplier_response_date");

                    b.Property<DateTime?>("SupplierResponseDeadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("supplier_response_deadline");

                    b.HasKey("ProcurementId");

                    b.HasIndex("BranchId");

                    b.HasIndex("RelatedPolicyId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Procurement");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ProcurementStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("historyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("changed_by_userID");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("from_status");

                    b.Property<int>("ProcurementId")
                        .HasColumnType("int")
                        .HasColumnName("procurementID");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("to_status");

                    b.HasKey("HistoryId");

                    b.HasIndex("ProcurementId");

                    b.ToTable("Procurement_Status_History");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("branch_id");

                    b.Property<string>("ContactPersonFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_person_fname");

                    b.Property<string>("ContactPersonLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_person_lname");

                    b.Property<string>("ContactPersonNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_person_number");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("supplier_name");

                    b.Property<DateTime?>("TerminatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("terminated_at");

                    b.Property<int?>("TerminatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("terminated_by_user_id");

                    b.Property<string>("TerminationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("termination_reason");

                    b.HasKey("SupplierId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.SupplierContract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contractID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("approval_date");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<int?>("LinkedPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("linked_policyID");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("risk_level");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    b.HasKey("ContractId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("LinkedPolicyId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Supplier_Contracts");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.SupplierItem", b =>
                {
                    b.Property<int>("SupplierItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplier_itemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierItemId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("item_name");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int")
                        .HasColumnName("quantity_available");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("SupplierItemId");

                    b.HasIndex("SupplierId", "ItemName")
                        .IsUnique();

                    b.ToTable("Supplier_Items");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.SupplierPolicy", b =>
                {
                    b.Property<int>("SupplierPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplier_policiesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierPolicyId"));

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_date");

                    b.Property<string>("ComplianceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("compliance_status");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policyID");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    b.HasKey("SupplierPolicyId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("SupplierId", "PolicyId")
                        .IsUnique();

                    b.ToTable("Supplier_Policies");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("branchId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastname");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit")
                        .HasColumnName("mustChangePassword");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.AuditLog", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ComplianceStatus", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.PolicyAssignment", "PolicyAssignment")
                        .WithOne("ComplianceStatus")
                        .HasForeignKey("TechNova_IT_Solutions.Models.ComplianceStatus", "AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ComplianceViolation", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TechNova_IT_Solutions.Models.User", "RaisedByUser")
                        .WithMany()
                        .HasForeignKey("RaisedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TechNova_IT_Solutions.Models.SupplierPolicy", "SupplierPolicy")
                        .WithMany()
                        .HasForeignKey("SupplierPolicyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PolicyAssignment");

                    b.Navigation("RaisedByUser");

                    b.Navigation("SupplierPolicy");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ExternalPolicyImport", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "ApprovedPolicy")
                        .WithMany()
                        .HasForeignKey("ApprovedPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechNova_IT_Solutions.Models.User", "ImportedByUser")
                        .WithMany()
                        .HasForeignKey("ImportedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TechNova_IT_Solutions.Models.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApprovedPolicy");

                    b.Navigation("ImportedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Policy", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Branch", "Branch")
                        .WithMany("Policies")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechNova_IT_Solutions.Models.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TechNova_IT_Solutions.Models.User", "UploadedByUser")
                        .WithMany("UploadedPolicies")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.PolicyAssignment", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "Policy")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechNova_IT_Solutions.Models.User", "User")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Procurement", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Branch", "Branch")
                        .WithMany("Procurements")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "RelatedPolicy")
                        .WithMany("Procurements")
                        .HasForeignKey("RelatedPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechNova_IT_Solutions.Models.Supplier", "Supplier")
                        .WithMany("Procurements")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("RelatedPolicy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ProcurementStatusHistory", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Procurement", "Procurement")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ProcurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procurement");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Supplier", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.SupplierContract", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "LinkedPolicy")
                        .WithMany()
                        .HasForeignKey("LinkedPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechNova_IT_Solutions.Models.Supplier", "Supplier")
                        .WithMany("SupplierContracts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("LinkedPolicy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.SupplierItem", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Supplier", "Supplier")
                        .WithMany("SupplierItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.SupplierPolicy", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "Policy")
                        .WithMany("SupplierPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechNova_IT_Solutions.Models.Supplier", "Supplier")
                        .WithMany("SupplierPolicies")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.User", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Branch", b =>
                {
                    b.Navigation("Policies");

                    b.Navigation("Procurements");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Policy", b =>
                {
                    b.Navigation("PolicyAssignments");

                    b.Navigation("Procurements");

                    b.Navigation("SupplierPolicies");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.PolicyAssignment", b =>
                {
                    b.Navigation("ComplianceStatus");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Procurement", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Supplier", b =>
                {
                    b.Navigation("Procurements");

                    b.Navigation("SupplierContracts");

                    b.Navigation("SupplierItems");

                    b.Navigation("SupplierPolicies");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("PolicyAssignments");

                    b.Navigation("UploadedPolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
