// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechNova_IT_Solutions.Data;

#nullable disable

namespace TechNova_IT_Solutions.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209233956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechNova_IT_Solutions.Models.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("logID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("action");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("logdate");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("module");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("Audit_Logs");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ComplianceStatus", b =>
                {
                    b.Property<int>("ComplianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("complianceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplianceId"));

                    b.Property<DateTime?>("AcknowledgedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("acknowledged_date");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignmentID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("ComplianceId");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.ToTable("Compliance_Status");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("policyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("DateUploaded")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_uploaded");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("PolicyTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("policy_title");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.HasKey("PolicyId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.PolicyAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_date");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policyID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    b.HasKey("AssignmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("PolicyId", "UserId")
                        .IsUnique();

                    b.ToTable("Policy_Assignments");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Procurement", b =>
                {
                    b.Property<int>("ProcurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("procurementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcurementId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("ItemName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("item_name");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("RelatedPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("related_policyID");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    b.HasKey("ProcurementId");

                    b.HasIndex("RelatedPolicyId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Procurement");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("ContactPersonFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_person_fname");

                    b.Property<string>("ContactPersonLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_person_lname");

                    b.Property<string>("ContactPersonNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_person_number");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("supplier_name");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.SupplierPolicy", b =>
                {
                    b.Property<int>("SupplierPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplier_policiesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierPolicyId"));

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_date");

                    b.Property<string>("ComplianceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("compliance_status");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policyID");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplierID");

                    b.HasKey("SupplierPolicyId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("SupplierId", "PolicyId")
                        .IsUnique();

                    b.ToTable("Supplier_Policies");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@technova.com",
                            FirstName = "System",
                            LastName = "Administrator",
                            Password = "Admin@123",
                            Role = "Admin",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.AuditLog", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.ComplianceStatus", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.PolicyAssignment", "PolicyAssignment")
                        .WithOne("ComplianceStatus")
                        .HasForeignKey("TechNova_IT_Solutions.Models.ComplianceStatus", "AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Policy", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.User", "UploadedByUser")
                        .WithMany("UploadedPolicies")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.PolicyAssignment", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "Policy")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechNova_IT_Solutions.Models.User", "User")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Procurement", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "RelatedPolicy")
                        .WithMany("Procurements")
                        .HasForeignKey("RelatedPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TechNova_IT_Solutions.Models.Supplier", "Supplier")
                        .WithMany("Procurements")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedPolicy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.SupplierPolicy", b =>
                {
                    b.HasOne("TechNova_IT_Solutions.Models.Policy", "Policy")
                        .WithMany("SupplierPolicies")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechNova_IT_Solutions.Models.Supplier", "Supplier")
                        .WithMany("SupplierPolicies")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Policy", b =>
                {
                    b.Navigation("PolicyAssignments");

                    b.Navigation("Procurements");

                    b.Navigation("SupplierPolicies");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.PolicyAssignment", b =>
                {
                    b.Navigation("ComplianceStatus");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.Supplier", b =>
                {
                    b.Navigation("Procurements");

                    b.Navigation("SupplierPolicies");
                });

            modelBuilder.Entity("TechNova_IT_Solutions.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("PolicyAssignments");

                    b.Navigation("UploadedPolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
